### ISSUE TITLE
Base OS architecture

### ISSUE THREAD

**Issue by stormanger** [mcbridematt/vyos-arm64-builder#3]
Hi, Matt

Whether the base OS needs to use x86 or arm64?
Can you provide the compiled arm64 vyos qcow2 download

Best wishes

**Comment by mcbridematt** [comment]
Hi,

You must run the build on an arm64 system.

Currently I don't provide compiled images as this is an experimental (unofficial) port. The VyOS project also [depends on subscriptions and donations](https://docs.vyos.io/en/latest/contributing/build-vyos.html) so I don't want to go against anyone accidentally.

**Comment by stormanger** [comment]
Thanks~
