### ISSUE TITLE
Build fails on mk-build-deps?

### ISSUE THREAD

**Issue by dsincl12** [mcbridematt/vyos-arm64-builder#9]
I get the following output when I try to build:

![Screenshot 2024-07-19 at 11 26 36 PM](https://github.com/user-attachments/assets/28b1ee75-cef7-4a1a-b78f-249d1fd0d120)

I've tried multiple times both on macOS, Debian and Ubuntu with the exact same result just different packages at times. Looking at the build-packages.sh script I can't really see anything odd or out of place on the line of the mk-build-deps either. Any ideas?

**Comment by mcbridematt** [comment]
Can you try the latest commit on the [rolling_ci](https://github.com/mcbridematt/vyos-arm64-builder/tree/rolling_ci) branch, including [vyos-build@vyos-build-2024-07-20](https://github.com/mcbridematt/vyos-build/tree/vyos-build-2024-07-20) ? VyOS have updated a few packages recently and some workarounds are needed to work with my Jenkinsfile parser.

**Comment by litesparkz** [comment]
Seems like the problem is with version of ddclient requested.

[ddclient-debian] Need to clone https://salsa.debian.org/debian/ddclient commit debian/3.10.0-3
Cloning into 'ddclient-debian'...
warning: redirecting to https://salsa.debian.org/debian/ddclient.git/
fatal: ambiguous argument 'debian/3.10.0-3': unknown revision or path not in the working tree.

Looks for version 3.10.0-3 on salsa debian but cant find it. The closest stable is 3.10.0-2

**Comment by litesparkz** [comment]
Appears to be the same problem on rolling-ci

**Comment by litesparkz** [comment]
ddclient working on rolling_ci
Will comment after complete build if there are any problems

**Comment by dsincl12** [comment]
ddclient worked for me as well, now it fails on the hostap package instead.

![Screenshot 2024-07-22 at 12 06 39 AM](https://github.com/user-attachments/assets/4f1239fd-7900-4891-bc6a-84c9f4e5d0a7)

**Comment by litesparkz** [comment]
Its worked for me

@dsincl12 
Did you delete the previous build directory before pulling rolling_ci branch?

Unfortunately cant get this to boot on a Rpi5

**Comment by dsincl12** [comment]
OK I got further but I can't really figure out what I'm doing wrong, because I feel like the process fails in random places even though everything is done from scratch everytime.

![Screenshot 2024-07-22 at 10 54 29 AM](https://github.com/user-attachments/assets/54f9daed-5e77-4915-8019-eb379a24691f)

1. I run the git --recursive command specified in the README.

2. I checkout the rolling_ci branch

3. I go into vyos-build and checkout the vyos-build-2024-07-20 branch

4. I go back and execute sudo ./build.sh

Am I missing some super obvious step here?

**Comment by litesparkz** [comment]
I just followed the standard setup instructions but pulled from rolling_ci:

git clone -b rolling_ci --recursive https://github.com/mcbridematt/vyos-arm64-builder.git

sudo ./build.sh

**Comment by dsincl12** [comment]
will try, ty :)

**Comment by litesparkz** [comment]
Dont forget to do a sudo rm -Rf vyos-arm64-builder before

**Comment by mcbridematt** [comment]
Yes, cloning a fresh repository with `--recursive` should set everything up correctly.

Other things to try include removing any old vyos-build docker images:
```
$ docker images
REPOSITORY                                                 TAG                    IMAGE ID       CREATED       SIZE
vyos-build-arm64                                           latest                 2b3fafbd6356   8 hours ago   2.48GB

$ docker rmi 2b3fafbd6356
```

If it still fails, there is probably an individual package missing or failed to build.
If you scroll up in the build log, live-build will likely mention the problem package in it's output.
It might help to do `sudo ./build.sh 2>&1 | tee build.log` to save a copy of the full build log.

I have mentioned in another issue ( https://github.com/mcbridematt/vyos-arm64-builder/issues/7#issuecomment-2164734558 ) that I have observed issues with the package build order not being fully deterministic. The package build method does need to be improved in the future.

**Comment by dsincl12** [comment]
OK, I will report back, building now and takes a while. Would love to automate this with one of my aarch64 boards and publish nightly iso images.

**Comment by litesparkz** [comment]
Any Ideas why this wont boot on a Rpi5 or what i'd have to do to get it to work?

**Comment by dsincl12** [comment]
it worked, awesome! thanks for your help everyone :)

**Comment by mcbridematt** [comment]
> Any Ideas why this wont boot on a Rpi5 or what i'd have to do to get it to work?

You will need a EFI capable bootloader, preferably a recent U-Boot (v2024.X+) that has [standard boot](https://docs.u-boot.org/en/stable/develop/bootstd.html) enabled.

I believe many of the "standard" Linux distributions (Ubuntu, SUSE, Fedora etc.) build their RPI images by bundling their "standard' Arm images with U-Boot + RPI firmware as the bootloader, so you might be able to use one of those as a starting point (like have a normal distro on microSD and VyOS on USB for testing, and modify the U-Boot config to preference USB ahead of microSD)

You might need to tweak the kernel config as well. I am focused on maintaining the config for our (Traverse) hardware, but if you find changes necessary for the RPI5, I encourage you to send them upstream to VyOS.
